In [1]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import TfidfVectorizer

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/admin1/anaconda3/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/admin1/anaconda3/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/home/admin1/anaconda3/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/home/admin1/anaconda3/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/home/admin1/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_5040/3729576770.py", line 1, in <module>
    import pandas as pd
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/admin1/anaconda3/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/admin1/anaconda3/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/home/admin1/anaconda3/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/home/admin1/anaconda3/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/home/admin1/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_5040/3729576770.py", line 1, in <module>
    import pandas as pd
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/home/admin1/anaconda3/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [7]:
movies = pd.read_csv("/home/admin1/Downloads/imdb_top_1000.csv")
movies = movies[['Series_Title','Genre','IMDB_Rating']]
movies.head()

               Series_Title                 Genre  IMDB_Rating
0  The Shawshank Redemption                 Drama          9.3
1             The Godfather          Crime, Drama          9.2
2           The Dark Knight  Action, Crime, Drama          9.0
3    The Godfather: Part II          Crime, Drama          9.0
4              12 Angry Men          Crime, Drama          9.0

In [9]:
tfidf = TfidfVectorizer()

genre_matrix = tfidf.fit_transform(movies['Genre'])

In [11]:
model = NearestNeighbors(
        metric='cosine',
        algorithm='brute',
        n_neighbors=6)

model.fit(genre_matrix)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=6)

In [13]:
def recommend_movie(movie_name):

    index = movies[movies['Series_Title'] == movie_name].index[0]

    distances, indices = model.kneighbors(
        genre_matrix[index],
        n_neighbors=6)

    print("Recommended Movies:\n")

    for i in indices.flatten()[1:]:
        print(movies.iloc[i]['Series_Title'])

In [ ]:
recommend_movie("The Dark Knight")

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [19]:
movies['Actual'] = movies['IMDB_Rating'].apply(lambda x: 1 if x >= 8 else 0)

In [21]:
movies['Predicted'] = movies['IMDB_Rating'].apply(lambda x: 1 if x >= 8 else 0)

In [23]:
y_true = movies['Actual']
y_pred = movies['Predicted']

acc = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)

print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0

### Naive Bayes Model for the Movie Recommendation

In [32]:
movies = pd.read_csv("/home/admin1/Downloads/imdb_top_1000.csv")

movies = movies[['Series_Title','Overview','IMDB_Rating']]

movies.dropna(inplace=True)

In [42]:
movies

,Series_Title,Overview,IMDB_Rating,label
0,The Shawshank Redemption,Two imprisoned men bond over a number of years...,9.3,1
1,The Godfather,An organized crime dynasty's aging patriarch t...,9.2,1
2,The Dark Knight,When the menace known as the Joker wreaks havo...,9.0,1
3,The Godfather: Part II,The early life and career of Vito Corleone in ...,9.0,1
4,12 Angry Men,A jury holdout attempts to prevent a miscarria...,9.0,1
...,...,...,...,...
995,Breakfast at Tiffany's,A young New York socialite becomes interested ...,7.6,0
996,Giant,Sprawling epic covering the life of a Texas ca...,7.6,0
997,From Here to Eternity,"In Hawaii in 1941, a private is cruelly punish...",7.6,0
998,Lifeboat,Several survivors of a torpedoed merchant ship...,7.6,0
999,The 39 Steps,A man in London tries to help a counter-espion...,7.6,0

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create label column
movies['label'] = movies['IMDB_Rating'].apply(lambda x: 1 if x >= 8 else 0)

# convert text to numbers
tfidf = TfidfVectorizer(stop_words='english')

X = tfidf.fit_transform(movies['Overview'])

y = movies['label']

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred))
print("Precision:", precision_score(y_test,y_pred))
print("Recall:", recall_score(y_test,y_pred))

Accuracy: 0.515
Precision: 0.5
Recall: 0.21649484536082475

In [40]:
print(movies.columns)

Index(['Series_Title', 'Overview', 'IMDB_Rating', 'label'], dtype='object')

In [44]:
def recommend_movie(description):

    text = tfidf.transform([description])

    prediction = model.predict(text)

    if prediction[0] == 1:
        print("This movie is likely to be Recommended")
    else:
        print("This movie may not be Recommended")

In [46]:
recommend_movie("A superhero fights crime and saves the city")
    prediction = model.predict(text)

    if prediction[0] == 1:
        print("This movie is likely to be Recommended")

This movie may not be Recommended